name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the push Docker image
        run: |
          docker login --username Elgius --password ${{ secrets.PAT  }} ghcr.io
          docker build . --tag ghcr.io/elgius/fenaka:latest
          docker push ghcr.io/elgius/fenaka:latest
